// GENERATED by scripts/rig/ingest_characters.mjs (npm run rig:ingest). DO NOT EDIT.
//
// Character bodies ingested from GLBs dropped in incoming/: each was validated against the
// Rig_Medium skeleton and had the clean KayKit clip set baked on, so it animates like the
// default classes. These are merged into VISUALS (see manifest.ts) as `custom_<name>` keys.
// No default entity dispatches to them; surface one by mapping an NPC/mob templateId or a
// player skin to its key.
import type { VisualDef } from './manifest';

export const CUSTOM_BODIES: Record<string, VisualDef> = {};
