// The COMPLETE per-ability visual spec, mirrored 1:1 from the Ability VFX
// Gallery source of truth (feature/ability-vfx-gallery: ability_specs.js,
// authored by 9 spec-author agents + locked references). Regenerate by
// re-running the projection in docs/ability-vfx-ingame.md when the gallery
// evolves. Consumed by the archetype sequencer (src/render/ability_vfx/).
// DATA-AS-CODE: one line per ability, trailing comments carry authoring intent.
// biome-ignore-all format: generated one-line-per-ability
import type { AbilityVfxFullSpec } from './ability_vfx_core';

export const ABILITY_VFX_FULL_SPECS: Record<string, AbilityVfxFullSpec> = {
  // ---- warrior ----
  heroic_strike: {"archetype":"strike","palette":"physical","power":1,"strike":{"swings":1,"arc":"horizontal"},"decal":"scorch","buff":{"orbit":"weaponGlow","o":{"rate":1.4,"size":0.3,"radius":0.5}},"impact":{"trail":"sweep","sparks":24,"light":0.6,"flipbook":false}}, // The EMPOWERED QUEUED SWING: keeps the kit's flat horizontal auto arc but hot amber - the buff.orbit weaponGlow is worn while queuedOnSwing is armed (painter queued hook, not an aura), releasing into a heavier sweep trail + a char scuff underfoot; deliberately no crack/motif at L1
  battle_shout: {"archetype":"shout","palette":"blood","power":1.05,"shout":{"radius":6},"buff":{"style":"raise","orbit":"weaponGlow","shellDur":1.5,"o":{"rate":1.8,"tickEvery":4}},"linger":3,"windupStyle":"none","rim":"#ff4636","impact":{"ring":2,"vRing":true,"light":3.2}}, // L1 war cry now sets the weapon alight, blood, red shimmer and light trails ride the blade for the buff's whole
  charge: {"archetype":"dash","palette":"physical","power":1.35,"spirit":null,"impact":{"ring":1.8,"sparks":34,"debris":true,"smoke":true,"light":1.5,"flipbook":false,"vRing":true,"trail":"sweep"},"tint":"#dfe9f4","accent":"#f2f7ff","hot":0.25,"rim":"#e5231b","windup":0.2,"windupStyle":"stance","buff":{"style":"raise","orbit":"speedlines","shellDur":1.1,"o":{"rate":2}},"debuff":{"orbit":"runes","o":{"n":4,"size":0.24,"tex":"chip","rate":0.7,"weave":0.03,"radius":0.85,"incline":0}},"motifs":["fissure"],"motifAt":"target","decal":"crack","linger":1.2}, // Signature gap, closer: caster rockets at the target trailing steel, grey speed ribbons and kicked, up dust. The debuff block is CRUSHING CHARGE's victim read (base Onrush only stuns 1s, no _root/_slow auras exist untalented): slow ground-grit chips circling the ankles for as long as the talent's charge_root/charge_slow live, and the root's band-start moment crashes the arrival (painter wornDebuff path)
  thunder_clap: {"archetype":"nova","palette":"storm","power":1,"nova":{"radius":8},"windup":0.3,"windupStyle":"vortex","motifs":["pillars"],"decal":"crack","impact":{"ring":1.3,"debris":true,"smoke":true,"light":0.6}}, // Weapon, into, dirt now ejects five sequential ground eruptions ringing the warrior, the seismic clap finally e
  hamstring: {"archetype":"strike","palette":"blood","power":0.7,"strike":{"swings":1,"arc":"low","bleed":true},"debuff":{"orbit":"speedlines","o":{"n":3,"rate":1.5,"size":0.2,"radius":1.15}},"impact":{"flipbook":false,"ring":false,"sparks":8,"trail":"low","blood":true,"light":0.5}}, // The low cut that hobbles: swing arc dropped to the shin-height 'low' reap to match the trail, and the VICTIM wears dragging red ankle speedlines for the snare's whole 15s (the debuff block worn via the hamstring_slow aura suffix map - a debuff band, never a buff's ground-disc/caster-pulse/swirl)
  bloodrage: {"archetype":"buff","palette":"blood","power":0.7,"buff":{"style":"raise","shellDur":1.5,"orbit":"heartbeat","o":{"bpm":96,"ringR":1,"tickEvery":2.8}},"linger":2,"windupStyle":"none","rim":"#9e1622","impact":{"blood":true,"light":1.3}}, // Blood, for, rage made literal: crimson heartbeat rings thump off the chest for the duration, pure racing pulse
  overpower: {"archetype":"strike","palette":"blood","power":1,"strike":{"swings":1,"arc":"uppercut"},"impact":{"flipbook":false,"ring":false,"vRing":true,"sparks":22,"smoke":false,"trail":"riposte","light":0.6}}, // The sharp crimson riposte: a rising reversal cut (opposite sweep to the kit's flat autos) snapped through the riposte trail with no windup, blood-tinged spark accent, and the sequencer's receiver flash paints the TARGET's brief red rim - the opening exploited; distinctly RED where autos stay steel
  execute: {"archetype":"strike","palette":"blood","power":1.6,"finisher":true,"strike":{"swings":1,"arc":"vertical","groundSlam":true},"windup":0.5,"windupStyle":"stance","impact":{"flipbook":true,"ring":true,"vRing":true,"sparks":60,"debris":true,"smoke":true,"trail":"overhead","blood":true,"light":0.8}}, // THE kill moment keeps no motif but becomes the kit's only full, stack cataclysm impact, everything on, so noth
  slam: {"archetype":"strike","palette":"physical","power":1.1,"strike":{"swings":1,"arc":"vertical","groundSlam":true},"windup":1.5,"windupStyle":"weapon","motifs":["fissure"],"decal":"crack","impact":{"trail":"overhead","debris":true,"smoke":true,"light":0.7}}, // The 1.5s charge now pays off seismically, the ground splits caster, to, target under the blow, breaking the ve
  whirlwind: {"archetype":"nova","palette":"physical","power":1.2,"nova":{"radius":8},"strike":{"swings":2,"arc":"horizontal"},"windup":0.3,"windupStyle":"vortex","motifs":["bladestorm"],"linger":1.5,"rim":"#dbe6f4","impact":{"flipbook":false,"ring":1.6,"vRing":false,"sparks":34,"debris":true,"smoke":false,"trail":"sweep","blood":true,"light":0.7}},
  cleave: {"archetype":"nova","palette":"physical","power":0.95,"nova":{"radius":5},"strike":{"swings":1,"arc":"sweep"},"windupStyle":"none","motifs":["bladestorm"],"impact":{"trail":"sweep","sparks":24,"flipbook":false,"ring":false,"light":0.6}}, // The wide flat reap (owner: sideways sword sweep, never the chop): arc 'sweep' is the extra-wide ribbon style, the rig swings the synthesized 1H_Melee_Attack_Slice_Horizontal, and the bladestorm whirl + sweep trail keep the multi-target read split from Thunder Clap's ground clap
  defensive_stance: {"archetype":"buff","palette":"physical","power":0.5,"buff":{"style":"raise","shellDur":2,"orbit":"plates","o":{"n":3,"size":1.3,"rate":0.8,"tickEvery":5}},"linger":2,"windup":0.4,"windupStyle":"stance","motifs":["barrier"],"rim":"#8fa8bd","impact":{"light":0.5}}, // Translucent plates snap into a guarding forward arc as the stance settles, block fantasy made literal, unique 
  demoralizing_shout: {"archetype":"shout","palette":"shadow","power":1.15,"shout":{"radius":10,"target":true},"motifs":["swarm"],"motifAt":"caster","windup":0.3,"windupStyle":"stance","linger":2,"rim":"#6b5a8c","impact":{"ring":2.6,"vRing":false,"sparks":0,"smoke":true,"flipbook":false,"debris":false,"light":2}},
  sunder_armor: {"archetype":"strike","palette":"physical","power":0.8,"strike":{"swings":1,"arc":"uppercut"},"impact":{"flipbook":false,"ring":false,"sparks":45,"debris":true,"smoke":false,"light":0.6},"decal":"crack"}, // Armor shear is metal, on, metal: no fireball, no shockwave, cranked sparks plus flying plate debris carry the 
  taunt: {"archetype":"shout","palette":"physical","power":0.85,"shout":{"radius":3,"target":true},"motifs":["claws"],"impact":{"ring":1.8,"vRing":true,"sparks":10,"light":2.6},"motifAt":"target"}, // Provoking bark: tight, sharp cry wave with a single small ground ring and one aggressive arc ribbon snapping t
  mortal_strike: {"archetype":"strike","palette":"physical","power":1.3,"strike":{"swings":1,"arc":"vertical","bleed":true},"windup":0.4,"windupStyle":"weapon","motifs":["crescents"],"motifAt":"target","linger":1.5,"rim":"#e5e9f0","impact":{"flipbook":false,"ring":false,"vRing":true,"sparks":40,"debris":true,"smoke":false,"trail":"overhead","blood":true,"light":0.8}},
  bloodthirst: {"archetype":"strike","palette":"blood","power":1.2,"strike":{"swings":2,"arc":"claws","bleed":true},"windupStyle":"none","motifs":["fountain"],"motifAt":"target","linger":1,"rim":"#c41022","impact":{"flipbook":false,"ring":1.4,"vRing":true,"sparks":34,"debris":true,"smoke":false,"trail":"x","blood":true,"light":0.6}},
  shield_slam: {"archetype":"strike","palette":"physical","power":1.2,"strike":{"swings":1,"arc":"thrust"},"windup":0.3,"windupStyle":"stance","motifs":["gavel"],"motifAt":"target","decal":"crack","linger":1,"rim":"#bcd0e8","impact":{"flipbook":false,"ring":1.6,"vRing":true,"sparks":16,"debris":true,"smoke":true,"blood":false,"light":1.4}},
  berserker_rage: {"archetype":"buff","palette":"blood","power":1.15,"self":true,"buff":{"style":"raise","orbit":"heartbeat","shellDur":1.5,"o":{"bpm":150,"ringR":2.4,"tickEvery":0.6}},"motifs":["claws"],"motifAt":"caster","linger":3.5,"windup":0.3,"windupStyle":"stance","rim":"#ff2a14","impact":{"flipbook":false,"ring":1.8,"vRing":true,"sparks":20,"debris":false,"smoke":false,"blood":true,"light":2.6}},
  // ---- mage ----
  fireball: {"archetype":"bolt","palette":"fire","power":1,"bolt":{"speed":17,"headScale":1.4,"coils":false,"jagged":false,"forkEvery":0},"dot":{"drip":"rise"},"linger":3,"windupStyle":"orb","hot":0.22,"windup":1.7,"decal":"scorch","impact":{"flipbook":true,"ring":true,"vRing":false,"sparks":36,"debris":true,"smoke":true}}, // De, runed: the molten orb swelling between the hands IS the first, spell fantasy, no circle needed.
  frost_armor: {"archetype":"buff","palette":"frost","power":0.7,"buff":{"style":"raise","shellDur":2,"orbit":"sparks","o":{"n":3,"size":0.5,"tex":"chip","rate":0.55,"weave":0.1,"incline":0.05,"tickEvery":4}},"linger":2,"rim":"#bfeaff"}, // Persistent frost, palette spark motes read as drifting ice, glint crystals, 'encased in frost' finally visible
  arcane_intellect: {"archetype":"buff","palette":"arcane","power":0.65,"buff":{"style":"raise","shellDur":1.2,"orbit":"halo","o":{"n":4,"size":0.3,"tex":"star","rate":1.1,"weave":0.08,"radius":0.5,"incline":0.15,"tickEvery":3}},"linger":2,"rim":"#c9a6ff"}, // Glinting sigils orbit the head for the duration, the intellect fantasy made literal; sparks freed for Frost Ar
  frostbolt: {"archetype":"bolt","palette":"frost","power":0.95,"bolt":{"speed":20,"headScale":1.1,"coils":true,"jagged":false,"forkEvery":0},"linger":2,"windupStyle":"vortex","accent":15267583,"impact":{"flipbook":false,"smoke":false,"debris":true,"sparks":18,"ring":false,"vRing":true}}, // Cold shatters instead of exploding: fire, flash flipbook and smoke removed, crystalline shard debris added, th
  conjure_water: {"archetype":"buff","palette":"frost","power":0.6,"buff":{"style":"raise","shellDur":1,"orbit":"none","o":{"tickEvery":3}},"linger":1.5,"windupStyle":"orb","motifs":["fountain"],"accent":10479871,"rim":"#aee7ff"}, // Fantasy made literal: arcing streams rain into the condensing orb between the palms, the flattest buff in the 
  conjure_food: {"archetype":"buff","palette":"arcane","power":0.6,"buff":{"style":"raise","shellDur":1,"orbit":"none","o":{"tickEvery":3.6}},"linger":1.5,"windup":2,"windupStyle":"vortex","motifs":["orbitals"],"accent":"#ffd9a0","rim":"#ffcf8a","impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":6,"debris":false,"smoke":true,"light":0.5}},
  fire_blast: {"archetype":"burst","palette":"fire","power":1.05,"accent":16765502,"impact":{"vRing":true,"smoke":false,"debris":false,"sparks":44,"flipbook":false,"ring":false}}, // The instant punch is a clean concussive pop, flipbook flash + heavy sparks only, no lingering dressing, the sn
  arcane_missiles: {"archetype":"bolt","palette":"arcane","power":0.95,"beam":{"dur":3,"ticks":3,"drain":false},"motifs":[],"impact":{"flipbook":false,"ring":false,"sparks":16,"vRing":false,"debris":false,"smoke":false},"windupStyle":"none","bolt":{"volley":4,"speed":22,"headScale":0.75,"coils":false,"jagged":false,"forkEvery":0}}, // Orbitals ARE the missiles, three orbs circle then slam one, two, three matching the 3 ticks; stock flipbook/ri
  polymorph: {"archetype":"cc","palette":"arcane","power":0.85,"cc":{"style":"poof"},"linger":4,"windupStyle":"runes","spirit":{"model":"sheep","path":"circle","at":"target","scale":1.05,"dur":2.5,"tint":"#ffd9ec"}}, // THE mage ritual keeps the kit's only rune circle: arcane ceremony into poof into the pinned ghost, sheep risin
  frost_nova: {"archetype":"nova","palette":"frost","power":1.35,"finisher":true,"nova":{"radius":8},"linger":3.5,"motifs":["pillars"],"impact":{"flipbook":false,"smoke":false,"debris":true,"sparks":26},"decal":"crack","screenFx":false}, // The finisher freeze earns a set, piece: ice pillars erupt around the ring while icy chunk debris flies, no fir
  arcane_explosion: {"archetype":"nova","palette":"arcane","power":1,"nova":{"radius":7},"windup":0.25,"windupStyle":"vortex","impact":{"flipbook":false,"smoke":false,"debris":false,"sparks":24,"ring":2,"vRing":false},"decal":"rune"}, // Spammable pulse stays motif, free by design; impact sculpted to an immaculate ring+sparks arcane wave, no flip
  scorch: {"archetype":"burst","palette":"fire","power":0.85,"burst":{"style":"ground"},"windupStyle":"none","accent":12073488,"impact":{"flipbook":true,"ring":false,"vRing":false,"sparks":10,"smoke":true,"debris":false},"decal":"scorch","hot":0.3}, // Intimate char, no fireworks: rings and flipbook stripped to a few ignition sparks and a rising smolder, the ta
  ice_barrier: {"archetype":"buff","palette":"frost","power":1.1,"buff":{"style":"raise","shellDur":3,"orbit":"plates","o":{"n":6,"size":0.75,"rate":0.55,"tickEvery":3.5}},"linger":4,"motifs":["barrier"],"barrier":true,"rim":"#58b8dc"}, // The L20 absorb IS a shield: translucent plates snap into a guarding arc at cast, splitting it from frost_armor
  pyroblast: {"archetype":"bolt","palette":"fire","power":1.5,"windup":2.5,"windupStyle":"ascend","hot":0.45,"bolt":{"speed":20,"style":"rock","headScale":1.8,"coils":false,"jagged":false,"forkEvery":0},"dot":{"drip":"fall"},"linger":4,"motifs":["fissure"],"motifAt":"target","decal":"crack","impact":{"flipbook":true,"ring":2,"vRing":true,"sparks":50,"debris":true,"smoke":true,"light":0.9}},
  flamestrike: {"archetype":"nova","palette":"fire","power":1.15,"nova":{"radius":7},"windupStyle":"none","burst":{"style":"skybeam"},"linger":2.5,"decal":"scorch","hot":0.5,"impact":{"flipbook":true,"ring":2,"vRing":false,"sparks":30,"debris":false,"smoke":true,"light":0.8}},
  // ---- rogue ----
  sinister_strike: {"archetype":"strike","palette":"physical","power":0.85,"strike":{"swings":1,"stars":false,"arc":"horizontal"},"impact":{"ring":false,"sparks":14,"trail":"arc"}}, // Spam builder goes lean, slash flash only, no ground ring, a short spit of sparks; the lone horizontal saber ar
  eviscerate: {"archetype":"strike","palette":"blood","power":1.45,"finisher":true,"strike":{"swings":2,"stars":false,"arc":"uppercut","bleed":true},"windup":0.2,"windupStyle":"stance","impact":{"debris":true,"sparks":36,"trail":"x","blood":true,"light":0.5}}, // The kit's one full, violence hit: debris torn loose plus a 36, spark spray on the twin cross, slash, maximal w
  garrote: {"archetype":"strike","palette":"blood","power":0.8,"strike":{"swings":1,"arc":"wire","bleed":true},"windupStyle":"none","dot":{"drip":"fall"},"debuff":{"orbit":"sparks","o":{"n":2,"size":0.16,"tex":"chip","rate":1.3,"weave":0.03,"radius":0.3,"incline":0}},"linger":3.5,"impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":0,"debris":false,"smoke":true,"blood":true,"light":0.3}}, // Throat Wire is a strangle, not a swing (owner): arc 'wire' draws the taut silver filament at the caster's fists + the victim's throat-height constriction pinch (sequencer wireContact) and the choke one-shot replaces the dagger arc (Garrote_Choke via attackByAbility); the vRing shing is dropped - subtle, close-quarters, sinister. The debuff block is the CHOKE worn: two tight crimson chips whipping at the throat for the bleed's whole 18s, riding the victim's unsuffixed garrote dot aura (the painter's debuff-first fallback path)
  backstab: {"archetype":"strike","palette":"shadow","power":1,"strike":{"swings":1,"stars":false,"arc":"thrust"},"windupStyle":"none","impact":{"flipbook":true,"ring":false,"sparks":8,"blood":true,"light":0.6}}, // The quiet kill: no flash, no ring, six sparks, silence from the blind spot IS the signature, opposite pole to 
  gouge: {"archetype":"strike","palette":"physical","power":0.85,"strike":{"swings":1,"stars":true,"arc":"claws"},"windupStyle":"none","impact":{"flipbook":false,"sparks":12},"motifs":["claws"]}, // Dirty eye, rake drops the burst flash and keeps only the low ground ripple, which now reads as the daze settli
  cheap_shot: {"archetype":"strike","palette":"physical","power":0.9,"strike":{"swings":1,"arc":"uppercut","stars":true},"windupStyle":"none","linger":2,"impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":6,"debris":false,"smoke":true,"light":0.35}},
  evasion: {"archetype":"buff","palette":"physical","power":1,"buff":{"style":"veil","shellDur":1.5,"orbit":"wings","o":{"ribs":4,"span":0.72,"flapRate":2.2,"tickEvery":1.6}},"linger":4,"rim":"#9fb8d8"}, // Untouchable blur: smoke, grey afterimage fans flicker behind the shoulders like ghost, images of dodges, uniqu
  sap: {"archetype":"cc","palette":"physical","power":0.7,"cc":{"style":"stars"},"linger":4,"windupStyle":"none","impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":4,"debris":false,"smoke":true,"trail":"overhead","light":0.3}},
  slice_and_dice: {"archetype":"buff","palette":"physical","power":1.05,"buff":{"style":"raise","shellDur":1.2,"orbit":"sparks","o":{"n":5,"size":0.24,"tex":"star","rate":1.9,"weave":0.3,"incline":0.28,"tickEvery":1.2}},"linger":4,"windupStyle":"none","motifs":["crescents"],"rim":"#e8c860"}, // Rune circle deleted (runes stay rare); the haste lives on the blades, both daggers shimmer and trail light, wh
  sprint: {"archetype":"buff","palette":"physical","power":0.7,"buff":{"style":"raise","shellDur":0.8,"orbit":"speedlines","o":{"rate":1.95,"tickEvery":0.9}},"linger":2,"windupStyle":"none","rim":"#cdd9e6","impact":{"smoke":true,"sparks":0,"ring":false}}, // Wind, blur streaks stream off the legs for the whole buff, the L10 'I am fast now' moment finally looks like i
  crippling_poison: {"archetype":"strike","palette":"venom","power":0.8,"strike":{"swings":1,"arc":"bite"},"windupStyle":"none","dot":{"drip":"fall"},"linger":3,"impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":6,"debris":false,"smoke":true,"trail":"low","light":0.4}},
  kidney_shot: {"archetype":"strike","palette":"blood","power":1.2,"strike":{"swings":1,"stars":true,"arc":"vertical"},"windupStyle":"none","motifs":["chains"],"impact":{"ring":false,"vRing":true,"sparks":20,"trail":"overhead"},"decal":"crack"}, // The stun made visible: chains snap up and bind through the stun, ground ring ceded to them, vertical shock rin
  expose_armor: {"archetype":"strike","palette":"physical","power":1.05,"strike":{"swings":2,"arc":"thrust"},"windupStyle":"none","decal":"crack","impact":{"flipbook":false,"ring":false,"vRing":1.3,"sparks":34,"debris":true,"smoke":false,"trail":"x","light":0.55}},
  ambush: {"archetype":"strike","palette":"shadow","power":1.4,"windup":0.5,"strike":{"swings":2,"stars":false,"arc":"vertical"},"windupStyle":"vortex","spirit":null,"impact":{"smoke":true,"sparks":18,"light":0.35,"flipbook":false,"ring":false,"vRing":false,"blood":true,"trail":"x"},"accent":"#6242a8","rim":"#2e2640","motifs":["implosion"],"motifAt":"target","linger":0.6,"screenFx":false}, // THE L16 reward: shadows coil inward (the held breath), then the dagger plunges as a spectral shadow, fox pounc
  rupture: {"archetype":"dot","palette":"blood","power":1.15,"dot":{"drip":"fall"},"linger":4,"windupStyle":"none","motifs":["fountain"],"motifAt":"target","debuff":{"orbit":"leaves","o":{"up":-0.55,"density":8,"spread":0.25}},"impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":0,"debris":false,"smoke":false,"blood":2.2,"light":0.4}}, // Bleed Out reads at BOTH ends now (owner: more obvious blood when struck): blood 2.2 gushes the contact spray, and the debuff block rides the victim's unsuffixed rupture dot aura (the garrote fallback path) as slow FALLING crimson motes - dripping blood for the bleed's whole 16s; the fountain + drip-fall linger stay the application flourish
  vanish: {"archetype":"buff","palette":"shadow","power":0.9,"self":true,"buff":{"style":"veil","shellDur":0.6,"orbit":"none","o":{"tickEvery":4.5}},"linger":2.5,"windupStyle":"none","motifs":["implosion"],"rim":"#241f33","impact":{"flipbook":false,"ring":1.4,"vRing":false,"sparks":0,"debris":false,"smoke":true,"light":0.25}},
  instant_poison: {"archetype":"buff","palette":"venom","power":0.7,"self":true,"buff":{"style":"raise","shellDur":1,"orbit":"weaponGlow","weaponAura":"#8fd455","weaponAuraScope":"tip","o":{"rate":1.7,"tickEvery":1.5}},"linger":3,"windup":0.4,"windupStyle":"weapon","rim":"#8fd455","impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":10,"debris":false,"smoke":false,"light":0.45}}, // Adder's Bite is the LESSER coat (8/swing vs Festering's 14): a green-TIPPED dagger (weaponAuraScope tip, the vertex-alpha ramp) for the full 30 min, plus its quick hand shimmer - deliberately subtler than Festering Venom's full-blade wash
  adrenaline_rush: {"archetype":"buff","palette":"blood","power":1.25,"buff":{"style":"raise","shellDur":1.5,"orbit":"heartbeat","o":{"bpm":128,"ringR":1.1,"tickEvery":0.7}},"linger":3.5,"motifs":["bladestorm"],"impact":{"light":0.6},"rim":"#e03a2e"}, // L20 capstone announces the frenzy, slash ribbons whirl around the rogue at release while the heartbeat rings s
  deadly_poison: {"archetype":"buff","palette":"venom","power":0.85,"self":true,"buff":{"style":"raise","shellDur":2,"orbit":"weaponGlow","weaponAura":"#58d63c","o":{"rate":0.6,"tickEvery":2.8}},"linger":4,"windup":0.6,"windupStyle":"weapon","motifs":["vines"],"dot":{"drip":"fall"},"tint":"#3f6d1f","rim":"#c8ff3c","impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":0,"debris":false,"smoke":true,"light":0.35}}, // Festering Venom is the BIGGER coat (14/swing vs Adder's 8), so it wears the bigger read (owner): the sickly-green full-blade weaponAura wash for the whole 30 min plus a slow weaponGlow band shedding venom motes off the hand; Adder's Bite keeps the subtle green tip
  blind: {"archetype":"cc","palette":"physical","power":0.8,"cc":{"style":"dust"},"linger":4,"windupStyle":"none","motifAt":"target","impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":0,"debris":true,"smoke":true,"light":0.3}}, // Dirt Toss THROWS (owner: not a swing): the Dirt_Throw scoop-and-fling one-shot via attackByAbility plus the cc 'dust' read - a khaki grit cone flung from the hand into the victim's eyes (color from the compact spec) - and the wander stars stay
  stealth: {"archetype":"buff","palette":"shadow","power":0.5,"buff":{"style":"veil","shellDur":2,"orbit":"none","o":{"tickEvery":6}},"linger":2,"windupStyle":"none","rim":"#3a3450","impact":{"smoke":true,"sparks":0,"light":0.3}}, // Kept deliberately quiet: no orbiters (they would betray concealment), short 2s shimmer as the veil settles int
  // ---- paladin ----
  seal_of_righteousness: {"archetype":"buff","palette":"gold","buff":{"style":"raise","shellDur":1.2,"orbit":"weaponGlow","o":{"rate":0.7,"tickEvery":4.5}},"power":0.8,"linger":3,"windupStyle":"weapon","windup":0.5,"decal":"rune","rim":"#ffd76a"}, // It's an imbue, not a rune ritual: gilded enchantment crawls up the mace with climbing sparks, and the weapon k
  holy_light: {"archetype":"heal","palette":"holy","power":1,"windupStyle":"ascend","windup":2.5,"motifs":["fountain"],"shaft":0.75,"impact":{"light":0.85}}, // The answered prayer lands as arcing light, streams raining onto the ally, splitting the big heal from Flash of
  devotion_aura: {"archetype":"buff","palette":"holy","buff":{"style":"raise","shellDur":2,"orbit":"halo","o":{"n":3,"size":0.4,"tex":"glow","rate":0.5,"weave":0.04,"incline":0.12,"tickEvery":9}},"power":0.6,"linger":2,"windupStyle":"none","rim":"#f7edc6"}, // Quiet 30, min litany: faint glinting devotional sigils orbit the armor, subtle enough to live with, and no lon
  judgement: {"archetype":"burst","palette":"gold","power":1.3,"finisher":true,"burst":{"style":"skybeam"},"windupStyle":"runes","windup":0.5,"motifs":["gavel","cross"],"impact":{"flipbook":true,"ring":2,"sparks":26,"light":0.7},"shaft":0.5,"decal":"scorch"}, // The verdict IS the radiant cross, flash: generic flipbook burst cut so the cross owns the skybeam's landing.
  blessing_of_might: {"archetype":"buff","palette":"gold","buff":{"style":"raise","shellDur":1.5,"orbit":"wings","o":{"ribs":7,"span":1.25,"flapRate":0.9,"tickEvery":8}},"power":0.7,"linger":2,"windupStyle":"none","rim":"#d4941e","impact":{"light":1.25,"sparks":14}}, // A true benediction: spectral golden wing, fans unfurl and flap behind the ally's shoulders for the buff, a ble
  divine_protection: {"archetype":"buff","palette":"holy","buff":{"style":"raise","shellDur":2.5,"orbit":"none","o":{"tickEvery":2.2}},"power":0.9,"linger":3.5,"windupStyle":"none","motifs":["barrier"],"barrier":true,"rim":"#ffe9a8"}, // Translucent plates snap into a guarding arc at cast then hand off to the orbiting facets, the bubble gets an a
  hammer_of_justice: {"archetype":"cc","palette":"gold","cc":{"style":"stars"},"power":1,"linger":3,"windupStyle":"none","motifs":["gavel"],"impact":{"flipbook":false,"ring":false,"sparks":18,"vRing":true,"debris":true,"light":0.9},"decal":"crack"}, // Golden chains snap up and bind through the stun, no ring, no flipbook, sparse sparks: a sentence, not an explo
  lay_on_hands: {"archetype":"heal","palette":"holy","power":1.6,"windup":0.8,"windupStyle":"vortex","shaft":0.45,"decal":"rune","motifs":["orbitals"],"impact":{"light":0.7,"debris":true}}, // The 10, minute miracle: the paladin's own light spirals inward off their body before pouring into the ally, th
  flash_of_light: {"archetype":"heal","palette":"holy","power":0.8,"windupStyle":"orb","windup":1.5,"shaft":false,"impact":{"vRing":true,"sparks":12,"light":1.15}}, // The humble handcast: a compact warm light, orb cupped between the hands over the 1.5s cast, deliberately small
  exorcism: {"archetype":"burst","palette":"holy","power":1.1,"burst":{"style":"ground"},"windupStyle":"none","spirit":{"model":"ghost","path":"rise","at":"target","scale":0.9,"dur":1.2}}, // Banishment made literal: on impact a ghostly spirit is TORN out of the target, rising and dissolving in the wh
  consecration: {"archetype":"nova","palette":"gold","nova":{"radius":8},"power":1,"linger":4,"windupStyle":"vortex","windup":0.5,"motifs":["pillars","cross"],"impact":{"flipbook":false,"light":0.6,"sparks":18},"decal":"rune"}, // Five sequential holy pillars erupt around the hallowed 8yd ring; center flipbook cut so the story stays on the
  righteous_fury: {"archetype":"buff","palette":"fire","buff":{"style":"raise","shellDur":1.5,"orbit":"heartbeat","o":{"bpm":70,"ringR":1.9,"tickEvery":6.5}},"power":0.75,"linger":2.5,"windupStyle":"stance","windup":0.4,"rim":"#ff7a2a"}, // The tank switch: grounded stance windup (dust, pebbles, late hand, glow), then flame, gold heartbeat rings thu
  retribution_aura: {"archetype":"buff","palette":"gold","power":0.65,"self":true,"buff":{"style":"raise","shellDur":1.5,"orbit":"sparks","o":{"n":3,"size":0.28,"tex":"rays","rate":1.6,"weave":0.25,"incline":0.3,"tickEvery":7}},"linger":3,"windupStyle":"none","rim":"#ffb347","impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":12,"debris":false,"smoke":false,"light":0.5}},
  // ---- hunter ----
  raptor_strike: {"archetype":"strike","palette":"physical","power":1.15,"strike":{"swings":1,"arc":"claws","bleed":true},"windup":0.5,"windupStyle":"stance","motifs":["claws"],"impact":{"trail":"x","flipbook":true,"ring":false,"vRing":true,"sparks":26,"debris":true,"smoke":false,"light":0.6,"blood":true},"spirit":null,"motifAt":"target","accent":"#e03a24"}, // Pinned raptor pounce kept; added grounded stance windup (dust, planted feet) so the on, next, swing wait reads
  aspect_of_the_hawk: {"archetype":"buff","palette":"storm","power":1,"buff":{"style":"raise","shellDur":2,"orbit":"wings","o":{"ribs":5,"span":0.75,"flapRate":2.1,"tickEvery":7.5}},"linger":3.5,"windupStyle":"ascend","spirit":null,"rim":"#8fc6ff","windup":0.3,"accent":"#cfe6ff","impact":{"ring":1.6,"vRing":true,"sparks":14,"debris":false,"smoke":false,"flipbook":false,"light":1.6}}, // The L4 unveil: a spectral hawk dives out of the sky onto the hunter and spectral wing fans keep beating behind
  serpent_sting: {"archetype":"dot","palette":"venom","power":0.85,"dot":{"drip":"fall"},"linger":4,"windupStyle":"none","motifs":["vines"],"impact":{"flipbook":true,"ring":false,"vRing":false,"sparks":8,"debris":true,"smoke":false,"light":0.5},"decal":"scorch"}, // Vines re, read as the spectral serpent coiling up the target; impact stripped to a wet fang, prick flicker so 
  arcane_shot: {"archetype":"bolt","palette":"arcane","power":0.95,"bolt":{"speed":40,"headScale":0.7,"coils":false,"jagged":false,"forkEvery":0,"tracer":true},"windupStyle":"none","impact":{"debris":false,"smoke":false}}, // Clean arcane pop: full flash and rings kept but no dirt or smoke, magic detonation, not a physical hit; splits
  concussive_shot: {"archetype":"bolt","palette":"physical","power":0.8,"bolt":{"speed":30,"headScale":0.9,"coils":false,"jagged":false,"forkEvery":0,"tracer":true},"linger":2,"windupStyle":"none","impact":{"flipbook":false,"sparks":0,"ring":true,"vRing":1.6,"debris":true,"smoke":true,"light":0.6}}, // Blunt daze reads blunt: no flash, zero sparks, just the shock ring, kicked debris and a dusty smoke thud, noth
  mongoose_bite: {"archetype":"strike","palette":"physical","power":0.95,"strike":{"swings":1,"arc":"bite"},"windupStyle":"none","impact":{"flipbook":false,"ring":false,"sparks":18,"debris":false,"smoke":false,"trail":"riposte","vRing":1.4,"light":0.6},"motifs":["claws"],"spirit":null,"accent":"#a4ff4f"}, // Intimate reflex, counter: no fireworks, just the vRing as the jaws' snap, plane and a short spark spit, pure s
  wing_clip: {"archetype":"strike","palette":"physical","power":0.7,"strike":{"swings":1,"arc":"horizontal","bleed":true},"linger":2,"windupStyle":"none","impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":6,"smoke":true,"trail":"low","debris":true,"blood":true,"light":0.4},"spirit":null}, // Humble low leg, hack: flash and rings removed, kept debris so the cut scuffs dirt at ankle height; the bleed d
  tame_beast: {"archetype":"summon","palette":"nature","power":0.8,"cc":{"style":"stars"},"windup":2.5,"windupStyle":"runes","spirit":null,"linger":3,"impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":8,"debris":false,"smoke":true,"light":0.6}}, // The hunter's one true ritual earns the kit's only rune circle over the 6s bond; explicit no spirit (owner 2026-07-23: the bull apparition made no sense on a tame - the beast being tamed is the creature in frame)
  dismiss_pet: {"archetype":"buff","palette":"nature","power":0.5,"buff":{"style":"veil","shellDur":0.8,"orbit":"none"},"linger":1.5,"windupStyle":"none","rim":"#86cfae","spirit":null}, // Quiet release, to, the, wild veil stays understated; explicit none so no circle flashes on a farewell; no wolf apparition (owner 2026-07-23)
  revive_pet: {"archetype":"summon","palette":"nature","power":0.75,"windup":1.5,"windupStyle":"ascend","shaft":0.6,"spirit":{"model":"wolf","path":"rise","at":"caster","scale":0.9,"dur":2.2,"tint":"#a8e8b0","dim":0.85}}, // Life gathers from the sky down onto the hunter during the cast, then pours into the leafy portal, resurrection
  aspect_of_the_monkey: {"archetype":"buff","palette":"physical","power":0.7,"buff":{"style":"raise","shellDur":1.2,"orbit":"sparks","o":{"n":2,"size":0.25,"tex":"paw","rate":2,"weave":0.35,"radius":0.9,"incline":0.1,"tickEvery":6}},"linger":3,"windupStyle":"none","spirit":null,"rim":"#8fd455","tint":"#9fe07a","accent":"#b6ff6e","impact":{"ring":false,"vRing":1.3,"sparks":22,"debris":false,"smoke":false,"flipbook":false,"light":1.2}},
  aspect_of_the_cheetah: {"archetype":"buff","palette":"physical","power":0.8,"buff":{"style":"raise","shellDur":1.5,"orbit":"speedlines","o":{"rate":1.4,"tickEvery":5.5}},"linger":3,"windupStyle":"stance","spirit":null,"rim":"#e8a34c","windup":0.3,"accent":"#ffc36b","impact":{"ring":1.4,"vRing":false,"sparks":10,"debris":true,"smoke":true,"flipbook":false,"light":1.4}}, // A spectral fox sprints a full lap around the hunter and wind, blur streaks stay on the legs, speed you can see
  aimed_shot: {"archetype":"bolt","palette":"physical","power":1.45,"finisher":true,"bolt":{"speed":48,"headScale":1,"coils":false,"jagged":false,"forkEvery":0,"tracer":true},"windup":2.5,"windupStyle":"weapon","impact":{"flipbook":true,"ring":true,"vRing":true,"sparks":48,"debris":true,"smoke":false,"light":0.7},"decal":"crack"}, // The kit's lone max, stack payoff after the 2.5s draw, every layer plus near, max sparks, smokeless because it'
  rapid_fire: {"archetype":"buff","palette":"physical","power":0.9,"buff":{"style":"raise","shellDur":1.2,"orbit":"heartbeat","o":{"bpm":126,"ringR":1.4,"tickEvery":3}},"linger":3,"windup":0.4,"windupStyle":"stance","bolt":{"speed":45,"headScale":0.6,"coils":false,"jagged":false,"forkEvery":0,"volley":5,"tracer":true},"impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":10,"debris":false,"smoke":false,"light":0.5},"self":true,"rim":"#ff6242"}, // Plant the feet (dust kick), then pulsing rings thump off the chest like a racing pulse for the haste window, a
  volley: {"archetype":"nova","palette":"physical","power":1.05,"nova":{"radius":8},"linger":3,"motifs":["fountain"],"motifAt":"target","windup":0.4,"windupStyle":"ascend","impact":{"flipbook":false,"ring":1.2,"vRing":false,"sparks":16,"debris":true,"smoke":true,"light":0.4}},
  feed_pet: {"archetype":"summon","palette":"nature","power":0.6,"windupStyle":"none","linger":2.5,"decal":"rune","spirit":null,"impact":{"flipbook":false,"ring":false,"vRing":1.1,"sparks":12,"debris":false,"smoke":false,"light":0.6}}, // Gentle feeding read: rune + soft sparks only, no wolf apparition (owner 2026-07-23)
  abandon_pet: {"archetype":"summon","palette":"nature","power":0.55,"windupStyle":"none","linger":2.2,"decal":"rune","spirit":null,"impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":0,"debris":false,"smoke":true,"light":0.4}}, // Pet-frame release twin of dismiss_pet: soft smoke farewell, no wolf apparition (owner 2026-07-23)
  // ---- priest ----
  smite: {"archetype":"burst","palette":"holy","power":0.9,"burst":{"style":"skybeam"},"windupStyle":"ascend","motifs":["cross"],"impact":{"debris":false,"smoke":false,"flipbook":true,"ring":true,"vRing":false,"sparks":26,"light":0.5},"shaft":0.5}, // Radiant cross, flash seals the skybeam; holy light kicks up no dirt or smoke, clean judgement, splits it from 
  lesser_heal: {"archetype":"heal","palette":"holy","power":0.65,"windupStyle":"orb","accent":15922943,"shaft":0.35}, // The novice prayer: a small warm orb cupped between the hands, deliberately humble so the later heals visibly o
  power_word_fortitude: {"archetype":"buff","palette":"holy","power":0.6,"buff":{"style":"raise","shellDur":1.5,"orbit":"heartbeat","o":{"bpm":48,"ringR":1.9,"tickEvery":5}},"linger":2,"windupStyle":"none","rim":"#ffd9a0"}, // Fortitude finally LOOKS like fortitude, golden pulse rings thumping off the ally's chest for the duration; ins
  shadow_word_pain: {"archetype":"dot","palette":"shadow","power":0.85,"dot":{"drip":"fall"},"linger":4,"motifs":["chains"],"impact":{"flipbook":false,"ring":false,"sparks":4,"vRing":false,"debris":false,"smoke":true,"light":0.6}}, // A whispered curse, not an explosion: dark shapes burst away from the victim and the stock fireworks are stripp
  power_word_shield: {"archetype":"buff","palette":"holy","power":0.95,"buff":{"style":"raise","shellDur":2.5,"orbit":"plates","o":{"n":3,"size":1.35,"rate":0.8,"tickEvery":2.5}},"linger":4,"windupStyle":"none","motifs":["barrier"],"barrier":true,"rim":"#eef4ff"}, // The iconic bubble earns its apply moment: translucent plates snap into a guarding arc before settling into the
  renew: {"archetype":"heal","palette":"holy","power":0.6,"linger":4,"accent":15922943,"shaft":false,"windup":0.25,"windupStyle":"orb"}, // HoT persistence + twin, split: steady trickle of rising golden motes now holds for linger 4 to sell the 15s tick; the staged 0.25s orb windup + Spellcast_Raise blessing gesture (manifest attackByAbility) give the instant cast a visible cast animation - kept gentle, it is a small HoT
  mind_blast: {"archetype":"burst","palette":"shadow","power":1.3,"finisher":true,"burst":{"style":"link"},"windupStyle":"vortex","spirit":{"model":"ghost","path":"rise","at":"target","scale":0.9,"dur":1.2},"hot":0.28,"impact":{"flipbook":true,"ring":true,"vRing":true,"sparks":20,"debris":false,"smoke":true}}, // The apocalyptic moment earns the kit's ONE spirit: dark power spirals inward during the 1.5s cast, and on deto
  heal: {"archetype":"heal","palette":"holy","power":1,"windupStyle":"runes","accent":15922943,"motifs":["fountain"]}, // The flagship 2.5s prayer's payoff: arcing streams of light rain onto the ally, so the long cast lands visibly 
  mind_flay: {"archetype":"beam","palette":"shadow","power":1.05,"beam":{"dur":3,"ticks":3,"drain":false},"windupStyle":"none","impact":{"flipbook":false,"ring":false,"debris":false,"smoke":true,"sparks":8,"vRing":false,"light":1.3}}, // Mental drain has no physical fireworks, ticks are stripped to a few sparks so the writhing drain, worm carries
  flash_heal: {"archetype":"heal","palette":"holy","power":0.8,"windupStyle":"none","accent":15922943,"hot":0.18,"shaft":false,"motifs":["implosion"],"impact":{"flipbook":false,"ring":false,"vRing":true,"sparks":18,"debris":false,"smoke":false,"light":1.2}}, // Urgency as exposure: white, hot core on the release splits it from lesser_heal's warm humble flare, the last s
  // ---- shaman ----
  lightning_bolt: {"archetype":"bolt","palette":"storm","windup":1.7,"power":1.25,"windupStyle":"runes","bolt":{"speed":30,"jagged":true,"coils":true,"forkEvery":0.09,"leader":true},"linger":3.2,"finisher":true},
  rockbiter_weapon: {"archetype":"buff","palette":"physical","power":0.75,"buff":{"style":"raise","shellDur":1.2,"orbit":"weaponGlow","o":{"rate":0.5,"tickEvery":6}},"linger":2.5,"windup":0.5,"windupStyle":"weapon","rim":"#b08850","decal":"crack","impact":{"ring":1.2,"debris":true,"sparks":6,"flipbook":false,"vRing":false},"tint":"#c8905a"}, // Pinned weaponGlow kept; 0.5s hold lets the earthen enchant visibly crawl up the weapon with climbing grit, spa
  healing_wave: {"archetype":"heal","palette":"frost","power":0.9,"windupStyle":"ascend","motifs":["fountain"],"shaft":0.65,"impact":{"vRing":1.2,"light":1.2,"sparks":10,"flipbook":false,"ring":false}}, // Fountain streams arc down onto the ally with the sky, light release, the shaman water, heal fantasy made liter
  earth_shock: {"archetype":"burst","palette":"physical","power":1.05,"burst":{"style":"ground"},"windup":0.4,"windupStyle":"stance","motifs":["fissure"],"impact":{"flipbook":false,"ring":1.3,"vRing":false,"sparks":8,"debris":true,"smoke":true,"light":0.7},"decal":"crack","tint":"#c8905a"}, // Grounded anticipation, dust and pebbles lift around the caster for a beat before the fault, line ground burst,
  lightning_shield: {"archetype":"buff","palette":"storm","power":0.65,"buff":{"style":"raise","shellDur":1.4,"orbit":"sparks","o":{"n":3,"size":0.45,"tex":"star","rate":1.9,"weave":0.3,"incline":0.35,"tickEvery":2}},"linger":4,"windup":0.4,"windupStyle":"orb","rim":"#7fd6ff","decal":"rune"}, // A crackling storm, orb forms between the hands then splits apart into the orbiting spark orbs, the level, 8 un
  flame_shock: {"archetype":"dot","palette":"fire","power":0.9,"dot":{"drip":"rise"},"linger":4,"windupStyle":"none","impact":{"ring":false,"vRing":false,"smoke":true,"sparks":18,"flipbook":true,"light":0.8},"decal":"scorch"}, // A searing brand, not a blast: shockwave rings stripped, smolder, smoke and a few embers only, so the hit reads
  flametongue_weapon: {"archetype":"buff","palette":"fire","power":0.75,"buff":{"style":"raise","shellDur":0.9,"orbit":"weaponGlow","weaponAura":"#ff5a26","o":{"rate":1.8,"tickEvery":2.5}},"linger":3,"windupStyle":"none","rim":"#ff8c3a","decal":"scorch","hot":0.15,"impact":{"flipbook":true,"ring":false,"vRing":false,"sparks":16,"debris":false,"smoke":true,"light":1.3}}, // Pyrebrand (owner: the weapon itself reads imbued for the WHOLE 5 min): warm red-orange weaponAura soak on the blade for the aura's full life; the fast weaponGlow band keeps shedding its sparse ember flicker off the hand
  frost_shock: {"archetype":"burst","palette":"frost","power":0.9,"burst":{"style":"link"},"linger":2.5,"windupStyle":"none","impact":{"flipbook":false,"sparks":0,"debris":true,"vRing":1.3,"ring":false,"smoke":false,"light":0.75},"screenFx":false,"decal":"crack"}, // Flash, freeze crack: fiery flipbook and spark fireworks removed, ice, shard debris added, a brittle shatter si
  frostbrand_weapon: {"archetype":"buff","palette":"frost","power":0.75,"buff":{"style":"raise","shellDur":1.6,"orbit":"weaponGlow","weaponAura":"#bfe4ff","o":{"rate":0.8,"tickEvery":4.5}},"linger":3,"windup":0.55,"windupStyle":"orb","rim":"#4f9fd8","impact":{"flipbook":false,"ring":false,"vRing":1.1,"sparks":0,"debris":true,"smoke":false,"light":0.9}}, // Rimebound (owner: same full-duration read as Pyrebrand): pale blue-white weaponAura rime on the blade for the aura's whole life; the slow weaponGlow band stays as the occasional frost-mote drift
  ghost_wolf: {"archetype":"buff","palette":"moon","power":0.6,"buff":{"style":"morph","shellDur":1,"orbit":"speedlines","o":{"rate":1.3,"tickEvery":3.5}},"linger":2,"windupStyle":"vortex","rim":"#b4a8e0","spirit":{"model":"wolf","path":"circle","at":"caster","scale":0.9,"dur":2.2,"tint":"#8fc8ff","dim":0.55}}, // Pinned wolf, circle spirit kept; the 2s cast becomes a true vortex (silver motes spiral inward to the implosio
  earthquake: {"archetype":"nova","palette":"physical","power":1.3,"nova":{"radius":8},"motifs":["fissure","pillars"],"motifAt":"target","linger":6,"windup":0.7,"windupStyle":"stance","decal":"crack","tint":"#c8905a","screenFx":true,"impact":{"flipbook":false,"ring":2,"vRing":false,"sparks":6,"debris":true,"smoke":true,"light":0.5}},
  stormstrike: {"archetype":"strike","palette":"storm","power":1.3,"strike":{"swings":2,"arc":"vertical","groundSlam":true,"stars":false},"windup":0.45,"windupStyle":"weapon","motifs":["bladestorm"],"impact":{"sparks":48,"debris":true,"flipbook":true,"ring":false,"vRing":true,"smoke":false,"trail":"x","light":1.5},"decal":"crack","rim":"#8fd6ff"}, // Storm, blade flurry: slash ribbons whirl around the shaman as both charged weapons release, with cranked elect
  // ---- warlock ----
  shadow_bolt: {"archetype":"bolt","palette":"shadow","power":1,"bolt":{"speed":21,"jagged":false,"coils":true,"forkEvery":0,"headScale":1.3},"windupStyle":"orb","motifs":["implosion"],"impact":{"ring":false,"vRing":false,"sparks":22,"smoke":true}}, // Void collapse: space sucks inward right before the hit and no shockwave rings escape, the bolt swallows, it do
  summon_imp: {"archetype":"summon","palette":"fire","power":0.85,"windupStyle":"runes","spirit":{"model":"demon","path":"pounce","at":"portal","scale":0.55,"dur":2.2,"tint":"#ff7a2e"},"linger":2,"decal":"scorch","impact":{"sparks":26,"smoke":true,"light":1.2}}, // Earns the rare rune circle (a true 5s summoning rite): ember runes etch the portal, then a small ghostly demon
  demon_skin: {"archetype":"buff","palette":"shadow","power":0.6,"buff":{"style":"raise","shellDur":2,"orbit":"plates","o":{"n":4,"size":0.85,"rate":0.85,"tickEvery":5}},"linger":3.5,"motifs":["barrier"],"rim":"#8b3ff5"}, // Chitin plates snap into a guarding arc on cast so the armor buff reads ARMOR at a glance, not another generic 
  immolate: {"archetype":"dot","palette":"fire","power":0.9,"dot":{"drip":"rise"},"linger":4,"windupStyle":"vortex","impact":{"ring":false,"vRing":false,"debris":false,"smoke":true,"sparks":36},"decal":"scorch"}, // Ignition, not concussion, flame flipbook, ember spray, and a smoke curl with zero shockwave rings; the target 
  corruption: {"archetype":"dot","palette":"venom","power":0.85,"dot":{"drip":"fall"},"linger":4,"windupStyle":"orb","impact":{"flipbook":false,"ring":false,"vRing":false,"debris":false,"sparks":6,"smoke":true},"motifs":["vines"]}, // Rot blooms wet and quiet, no fireworks, just a smoky seep; the identity stays in the festering ichor orb windu
  life_tap: {"archetype":"buff","palette":"blood","power":0.65,"buff":{"style":"raise","shellDur":0.8,"orbit":"heartbeat","o":{"bpm":58,"ringR":1.7,"tickEvery":4}},"rim":"#ff4a5a","linger":1.5,"impact":{"blood":true}}, // You pay in heartbeats, crimson pulse rings thump off the chest as health becomes mana; the kit's only heartbea
  summon_voidwalker: {"archetype":"summon","palette":"shadow","power":1.1,"windupStyle":"vortex","spirit":{"model":"demon","path":"rise","at":"portal","scale":1.35,"dur":2.5,"tint":"#5a3bd6","dim":0.85},"motifs":["implosion"],"decal":"portal","linger":2.5,"impact":{"smoke":true,"debris":true,"light":1.2}}, // THE ritual: the heavyweight rune circle spins up the void portal and a hulking spectral voidwalker rises out o
  curse_of_agony: {"archetype":"dot","palette":"shadow","power":1.05,"dot":{"drip":"fall"},"linger":4,"motifs":["swarm"],"impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":10},"decal":"rune"}, // The curse seats with a burst of dark shapes fleeing the victim, dread made visible, while the stock explosion 
  drain_life: {"archetype":"beam","palette":"blood","power":1,"beam":{"dur":3,"ticks":5,"drain":true},"impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":12,"debris":false,"smoke":false,"blood":true,"light":1.6},"linger":2}, // Intimate siphon, each drain tick lands as a bare fleck so the sinuous toward, caster flow stays the whole pict
  fear: {"archetype":"cc","palette":"shadow","power":0.85,"cc":{"style":"tendrils"},"linger":4,"windupStyle":"vortex","spirit":{"model":"demon","path":"rise","at":"target","scale":1,"dur":2.2,"tint":"#b9a4ff","dim":0.5},"impact":{"light":1.5}}, // Terror gathers as shadows spiral into the warlock, then a wailing ghost rises through the victim as the tendri
  searing_pain: {"archetype":"bolt","palette":"fire","power":0.95,"bolt":{"speed":30,"jagged":false,"coils":false,"forkEvery":0,"headScale":0.9},"windupStyle":"orb","accent":16765502,"impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":44,"debris":false,"smoke":false,"light":1.4}}, // White, hot needle: no explosion at all, just a grinding spray of sparks off the point of contact, the anti, sh
  shadowburn: {"archetype":"burst","palette":"shadow","power":1.4,"finisher":true,"burst":{"style":"skybeam"},"motifs":["implosion"],"motifAt":"target","linger":2,"hot":0.2,"impact":{"flipbook":true,"ring":true,"vRing":true,"sparks":50,"debris":true,"smoke":true}}, // The kit's one cataclysm, every impact layer on under the shadowflame skybeam. The implosion motif sucks space inward at the victim just before the column lands - a void-collapse read that sets it clearly apart from Skyfall's outward radiant crescents
  summon_succubus: {"archetype":"summon","palette":"shadow","power":0.9,"windup":2,"windupStyle":"runes","spirit":{"model":"ghost","path":"circle","at":"portal","scale":0.9,"dur":2.2,"tint":"#e88ac8","dim":0.8},"motifs":["crescents"],"decal":"rune","linger":2,"rim":"#d966b8","impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":18,"debris":false,"smoke":true,"light":1.1}},
  summon_felhunter: {"archetype":"summon","palette":"shadow","power":0.95,"windup":2,"windupStyle":"orb","spirit":{"model":"spider","path":"pounce","at":"portal","scale":0.85,"dur":2,"tint":"#9fe855","dim":0.85},"motifs":["orbitals"],"decal":"rune","linger":2,"accent":"#b48cff","impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":24,"debris":false,"smoke":true,"light":1.2}},
  summon_felguard: {"archetype":"summon","palette":"shadow","power":1.15,"windup":2.2,"windupStyle":"stance","spirit":{"model":"voidwalker","path":"lunge","at":"portal","scale":1.25,"dur":2.2,"tint":"#e8a055","dim":0.75},"motifs":["bladestorm"],"decal":"crack","linger":2.5,"impact":{"flipbook":false,"ring":1.4,"vRing":false,"sparks":20,"debris":true,"smoke":true,"light":1.1}},
  summon_infernal: {"archetype":"summon","palette":"fire","power":1.6,"windup":2.4,"windupStyle":"ascend","spirit":{"model":"demon","path":"swoop","at":"portal","scale":1.4,"dur":2.5,"tint":"#ff7a2a","dim":0.8},"motifs":["fissure"],"decal":"scorch","linger":3,"impact":{"flipbook":true,"ring":2,"vRing":true,"sparks":40,"debris":true,"smoke":true,"light":2}},
  summon_doomguard: {"archetype":"summon","palette":"shadow","power":1.45,"windup":2.4,"windupStyle":"runes","spirit":{"model":"ghost","path":"rise","at":"portal","scale":1.35,"dur":2.5,"tint":"#7a5df0","dim":0.65},"motifs":["chains"],"decal":"rune","linger":3,"rim":"#8b2a4a","impact":{"flipbook":false,"ring":false,"vRing":true,"sparks":14,"debris":false,"smoke":true,"light":1.7}},
  rain_of_fire: {"archetype":"dot","palette":"fire","power":1.15,"dot":{"drip":"fall"},"motifs":["pillars"],"motifAt":"target","linger":4,"windup":0.4,"windupStyle":"ascend","decal":"scorch","impact":{"flipbook":true,"ring":false,"vRing":false,"sparks":30,"debris":true,"smoke":true,"light":0.9}},
  // ---- druid ----
  wrath: {"archetype":"bolt","palette":"nature","power":0.9,"bolt":{"speed":24,"jagged":false,"coils":true,"forkEvery":0,"headScale":1},"windupStyle":"orb","impact":{"light":0.6}}, // Rune circle gone: a crackling verdant orb charges between the hands and the bolt coils with spiraling leaf mot
  healing_touch: {"archetype":"heal","palette":"nature","power":1,"windupStyle":"ascend","motifs":["fountain"]}, // Fountain: arcing life, streams rain onto the ally as the canopy light releases, the flagship heal's set, piece
  mark_of_the_wild: {"archetype":"buff","palette":"nature","power":0.6,"buff":{"style":"raise","shellDur":1.5,"orbit":"leaves","o":{"density":9,"spread":1.25,"up":0.65,"tickEvery":6}},"linger":3,"windupStyle":"none","spirit":{"model":"stag","path":"circle","at":"caster","scale":1,"dur":2.2,"tint":"#d6e6a3","dim":0.62},"rim":"#b9d178"}, // The level, 1 clip: a ghostly stag runs one proud lap around the blessed ally while the leaf motes spiral up, t
  moonfire: {"archetype":"dot","palette":"moon","power":0.95,"dot":{"drip":"rise"},"burst":{"style":"skybeam"},"linger":4,"hot":0.3,"decal":"rune","impact":{"light":0.5,"ring":false,"flipbook":false,"sparks":10}}, // Skybeam burst, a column of moonlight crashes onto the target (the iconic moonfire read), and linger 4 keeps lu
  rejuvenation: {"archetype":"heal","palette":"nature","power":0.65,"linger":4,"shaft":false}, // Linger 4 so the sparse rising leaf motes persist and sell the 12s HoT; stays the softest, quietest heal vs Reg
  thorns: {"archetype":"buff","palette":"venom","power":0.65,"buff":{"style":"raise","shellDur":2,"orbit":"sparks","o":{"n":5,"size":0.3,"tex":"chip","rate":0.65,"weave":0.05,"incline":0.1,"radius":0.8,"tickEvery":5}},"linger":3.5,"windupStyle":"none","motifs":["vines"],"rim":"#3f7a2e"}, // Vines coil up and wrap the blessed target as the bramble armor takes, thorns finally LOOK like growth, not a g
  entangling_roots: {"archetype":"cc","palette":"nature","power":0.75,"cc":{"style":"tendrils"},"linger":4,"windupStyle":"stance","motifs":["vines","chains"],"impact":{"ring":false,"light":0.35,"debris":true,"smoke":true},"decal":"crack"}, // Grounded stance windup: dust and pebbles shiver as the earth cracks underfoot, selling the vines about to erup
  bear_form: {"archetype":"buff","palette":"nature","power":0.75,"buff":{"style":"morph","shellDur":1,"orbit":"none","o":{"tickEvery":5.5}},"linger":2,"decal":"crack","rim":"#9a6a3a","impact":{"ring":1.4,"smoke":true,"debris":true},"spirit":{"model":"bear","path":"rise","at":"caster","scale":1.15,"dur":1.8,"tint":"#b97a45","dim":0.85}}, // Toggle: orbit none + short 2s linger on the post, poof shell; power up to 0.9 for bear mass, splitting it from
  bear_charge: {"archetype":"dash","palette":"physical","power":1,"spirit":{"model":"bear","path":"lunge","at":"caster","scale":1.15,"dur":1.1,"tint":"#b97a45","dim":0.9},"impact":{"ring":1.5,"debris":true,"smoke":true,"sparks":14,"light":0.6}}, // A spectral bear lunges along the gallop, overlaying the charging druid; L10's answer to the warrior's bull.
  maul: {"archetype":"strike","palette":"physical","power":1,"strike":{"swings":1,"stars":false,"arc":"claws"},"impact":{"debris":true,"sparks":10,"trail":"arc","ring":1.1,"light":0.4}}, // Clean beast paw strike: a single clawed arc with a little dirt debris - toned down from the over-the-top ground-slam (groundSlam/overhead/crack/smoke/1.8 ring dropped) to a crisp swipe
  growl: {"archetype":"shout","palette":"physical","power":1.05,"shout":{"radius":4,"target":true},"impact":{"ring":2.2,"vRing":true,"sparks":10,"debris":true,"smoke":true,"light":1.6},"rim":"#ff5f45","motifAt":"target"}, // Taunt utility: short bear, roar wave, one small vertical ring cone toward the target and a faint ground ripple
  demoralizing_roar: {"archetype":"shout","palette":"physical","power":1.1,"shout":{"radius":8},"motifs":["swarm"],"impact":{"ring":3,"light":1.3,"smoke":true,"debris":true,"sparks":6},"rim":"#7d6b9e"}, // Swarm: courage visibly flees, dark shapes scatter off the demoralized enemies, splitting the big roar from Gro
  cat_form: {"archetype":"buff","palette":"moon","power":0.7,"buff":{"style":"morph","shellDur":0.8,"orbit":"none","o":{"tickEvery":3}},"linger":2,"decal":"crack","rim":"#8fa3c8","spirit":{"model":"wolf","path":"pounce","at":"caster","scale":0.85,"dur":1.4,"tint":"#aebcdc","dim":0.75}}, // Split from Bear Form twin: moonlit, silver palette (wolf under the moon, echoing Prowl), quicker leaner poof (
  prowl: {"archetype":"buff","palette":"moon","power":0.5,"buff":{"style":"veil","shellDur":1.5,"orbit":"none","o":{"tickEvery":8}},"linger":2,"rim":"#26303f","spirit":{"model":"fox","path":"circle","at":"caster","scale":0.6,"dur":2,"tint":"#31405c","dim":0.3}}, // Stealth toggle: orbit none (nothing glowing should circle a stalker) with a short 2s linger on the settling mi
  rake: {"archetype":"strike","palette":"blood","power":0.9,"strike":{"swings":1,"stars":false,"arc":"claws","bleed":true},"linger":4,"impact":{"flipbook":false,"ring":false,"sparks":8,"blood":true,"light":0.4}}, // Intimate bleed opener: no flipbook, no ring, 8 sparks, a quiet tearing cut that lets the lingering wound speak
  claw: {"archetype":"strike","palette":"physical","power":0.85,"strike":{"swings":1,"stars":false,"arc":"claws"},"impact":{"ring":false,"sparks":8,"trail":"arc","light":0.3}}, // Light spam builder de, fireworked: no shockwave ring, just the clean big-cat scratch (triple gash) with the spark spray pulled back to 8 so it reads as a claw, not a burst.
  regrowth: {"archetype":"heal","palette":"nature","power":0.9,"linger":3.5,"windupStyle":"vortex","shaft":0.45,"impact":{"flipbook":true,"vRing":true,"sparks":12}}, // Life, motes vortex inward around the druid then release as the fast bloom, the inverse of Healing Touch's desc
  ferocious_bite: {"archetype":"strike","palette":"blood","power":1.3,"strike":{"swings":1,"stars":false,"arc":"bite","bleed":true},"impact":{"vRing":true,"debris":true,"sparks":30,"trail":"x","blood":true,"ring":1.5,"smoke":false,"flipbook":false,"light":0.5},"spirit":{"model":"wolf","path":"pounce","at":"target","scale":0.9,"dur":1,"tint":"#e8ecff","dim":0.7},"linger":1.5}, // Finisher crunch: vertical ring and debris on the jaw snap, the kit's heaviest melee impact, towering over Rake
  barkskin: {"archetype":"buff","palette":"nature","power":0.7,"buff":{"style":"raise","shellDur":2.5,"orbit":"plates","o":{"n":6,"size":1.2,"rate":0.5,"tickEvery":5}},"linger":4,"windupStyle":"none","motifs":["barrier"],"rim":"#7a8f66","decal":"crack","impact":{"ring":1.2,"light":0.5,"debris":true,"smoke":false}}, // Barrier plates snap into a guarding arc as the skin hardens to bark, the panic button reads as a block, distin
  swipe: {"archetype":"nova","palette":"physical","power":0.85,"nova":{"radius":5},"strike":{"swings":1,"arc":"claws"},"impact":{"trail":"sweep","light":0.5,"sparks":18,"debris":true,"smoke":true}}, // Claw, rake gashes layered over the low nova ring so the bear AoE reads paw, swipe, not shockwave.
  starfire: {"archetype":"bolt","palette":"moon","power":1.5,"finisher":true,"bolt":{"speed":18,"jagged":false,"coils":true,"forkEvery":0,"headScale":1.7},"windup":2.5,"windupStyle":"ascend","motifs":["crescents"],"decal":"scorch","impact":{"flipbook":true,"ring":1.8,"vRing":true,"sparks":40,"debris":true,"smoke":true,"light":0.5}}, // Crescents: twin moon, blades sweep through the target at the stellar impact. windupStyle 'ascend' gives the long finisher a rising gather-the-starlight charge cue (was 'runes', which read as no charge); the stellar hit now lands with a bigger 1.8 ground ring + vertical halo so the payoff finally matches the buildup
  travel_form: {"archetype":"buff","palette":"nature","power":0.6,"buff":{"style":"morph","shellDur":0.8,"orbit":"speedlines","o":{"rate":1.7,"tickEvery":3}},"linger":2,"windupStyle":"none","rim":"#d9c060","spirit":{"model":"stag","path":"rise","at":"caster","scale":1,"dur":1.5,"tint":"#bfe39a","dim":0.7},"impact":{"ring":false,"sparks":0,"smoke":true,"light":0.5}},
  enrage: {"archetype":"buff","palette":"blood","power":0.8,"buff":{"style":"raise","shellDur":1.2,"orbit":"heartbeat","o":{"bpm":92,"ringR":1.45,"tickEvery":2.5}},"linger":3,"windup":0.3,"windupStyle":"stance","motifs":["claws"],"motifAt":"caster","rim":"#d84a2a","decal":"crack","impact":{"flipbook":false,"ring":1.2,"vRing":false,"sparks":10,"debris":true,"smoke":true,"light":0.8}},
  bash: {"archetype":"strike","palette":"physical","power":0.9,"strike":{"swings":1,"arc":"horizontal","stars":true},"windupStyle":"none","linger":1.5,"impact":{"flipbook":false,"ring":false,"vRing":1.3,"sparks":12,"debris":true,"smoke":true,"trail":"arc","light":0.5}},
  faerie_fire: {"archetype":"bolt","palette":"nature","power":0.6,"bolt":{"speed":22,"style":"wisp","jagged":false,"coils":false,"forkEvery":0,"headScale":0.7},"windupStyle":"none","linger":4,"motifs":["orbitals"],"motifAt":"target","accent":"#e79aff","impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":6,"debris":false,"smoke":false,"light":0.4,"liteAudio":true}},
  hibernate: {"archetype":"cc","palette":"nature","power":0.7,"cc":{"style":"stars"},"windup":1.5,"windupStyle":"orb","linger":4,"accent":"#cfe8ff","impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":8,"debris":false,"smoke":true,"light":0.4}},
  dash: {"archetype":"buff","palette":"moon","power":0.7,"buff":{"style":"raise","shellDur":0.8,"orbit":"speedlines","o":{"rate":2,"tickEvery":1.8}},"linger":3,"windupStyle":"none","rim":"#6f8fd8","spirit":{"model":"wolf","path":"lunge","at":"caster","scale":0.85,"dur":1.2,"tint":"#aebcdc","dim":0.6},"impact":{"ring":false,"sparks":0,"smoke":true,"light":0.4}},
  pounce: {"archetype":"strike","palette":"moon","power":0.95,"strike":{"swings":1,"arc":"claws","stars":true},"windupStyle":"none","linger":1.5,"impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":6,"debris":false,"smoke":true,"trail":"low","light":0.3}},
  insect_swarm: {"archetype":"dot","palette":"nature","power":0.9,"dot":{"drip":"fall"},"linger":4,"windupStyle":"none","motifs":["swarm"],"motifAt":"target","accent":"#b7c94a","impact":{"flipbook":false,"ring":false,"vRing":false,"sparks":14,"debris":false,"smoke":false,"light":0.4}},
  tigers_fury: {"archetype":"buff","palette":"blood","power":0.9,"buff":{"style":"raise","shellDur":1,"orbit":"heartbeat","o":{"bpm":118,"ringR":1.05,"tickEvery":1.2}},"linger":3,"windupStyle":"none","rim":"#b81f3c","spirit":{"model":"wolf","path":"rise","at":"caster","scale":0.9,"dur":1.2,"tint":"#ff6a5a","dim":0.6},"impact":{"flipbook":false,"ring":false,"sparks":10,"blood":true,"light":0.7}},
  rip: {"archetype":"dot","palette":"blood","power":1.1,"dot":{"drip":"fall"},"linger":4,"windupStyle":"none","motifs":["claws"],"motifAt":"target","impact":{"flipbook":false,"ring":false,"vRing":true,"sparks":8,"debris":false,"smoke":false,"blood":true,"light":0.5}},
  hurricane: {"archetype":"nova","palette":"storm","power":1.2,"nova":{"radius":8},"windup":0.6,"windupStyle":"ascend","motifs":["bladestorm","fountain"],"linger":6,"impact":{"flipbook":false,"ring":2,"vRing":false,"sparks":22,"debris":true,"smoke":true,"light":1.1}},
};
