// Per-ability visual identity for the in-game ability VFX system.
// DATA-AS-CODE, projected from the Ability VFX Gallery authored specs
// (feature/ability-vfx-gallery: ability_specs.js). Regenerate with the
// projection snippet in docs/ability-vfx-ingame.md when the gallery evolves.
// Compact keys: c=color p=palette pw=power sp=sparks rg=ringScale vr=vRing
// db=debris sm=smoke bl=blood li=lightScale b={v:speed,h:headScale,j:jagged,
// co:coils,vl:volley} bo=buffOrbit lg=linger wu=windup spin fin a=archetype.
import type { AbilityVfxSpec } from './ability_vfx_core';

export const ABILITY_VFX_SPECS: Record<string, AbilityVfxSpec> = {
  heroic_strike: {
    c: '#ffa03c',
    p: 'physical',
    pw: 1,
    sp: 24,
    li: 0.6,
    bo: 'weaponGlow',
    a: 'strike',
  },
  battle_shout: {
    c: '#ff4636',
    p: 'blood',
    pw: 1.05,
    rg: 2,
    vr: 1,
    li: 3.2,
    bo: 'weaponGlow',
    lg: 3,
    a: 'shout',
  },
  // Growverse original (no upstream spec). Battle Shout's sibling in the
  // warrior_shout exclusive group, so it shares that shout anatomy; the gold
  // palette and steadier ring read as the endurance buff rather than the rage one.
  commanding_shout: {
    c: '#ffc247',
    p: 'gold',
    pw: 1,
    rg: 1.9,
    vr: 1,
    li: 3,
    bo: 'weaponGlow',
    lg: 3.2,
    a: 'shout',
  },
  charge: {
    c: '#e5231b',
    p: 'physical',
    pw: 1.35,
    sp: 34,
    rg: 1.8,
    vr: 1,
    db: 1,
    sm: 1,
    li: 1.5,
    bo: 'speedlines',
    lg: 1.2,
    wu: 0.2,
    a: 'dash',
  },
  thunder_clap: { c: '#8fd0ff', p: 'storm', rg: 1.3, db: 1, sm: 1, li: 0.6, wu: 0.3, a: 'nova' },
  hamstring: {
    c: '#d41f2e',
    p: 'blood',
    pw: 0.7,
    sp: 8,
    bl: 1,
    li: 0.5,
    bo: 'speedlines',
    a: 'strike',
  },
  bloodrage: {
    c: '#9e1622',
    p: 'blood',
    pw: 0.7,
    bl: 1,
    li: 1.3,
    bo: 'heartbeat',
    lg: 2,
    a: 'buff',
  },
  overpower: { c: '#e5233a', p: 'blood', sp: 22, vr: 1, li: 0.6, a: 'strike' },
  execute: {
    c: '#d41f2e',
    p: 'blood',
    pw: 1.6,
    sp: 60,
    rg: 1,
    vr: 1,
    db: 1,
    sm: 1,
    bl: 1,
    li: 0.8,
    wu: 0.5,
    fin: 1,
    a: 'strike',
  },
  slam: { c: '#dfe6ee', p: 'physical', pw: 1.1, db: 1, sm: 1, li: 0.7, wu: 1.5, a: 'strike' },
  whirlwind: {
    c: '#dbe6f4',
    p: 'physical',
    pw: 1.2,
    sp: 34,
    rg: 1.6,
    db: 1,
    bl: 1,
    li: 0.7,
    lg: 1.5,
    wu: 0.3,
    a: 'nova',
  },
  cleave: { c: '#dfe6ee', p: 'physical', pw: 0.95, sp: 24, li: 0.6, a: 'nova' },
  defensive_stance: {
    c: '#8fa8bd',
    p: 'physical',
    pw: 0.5,
    li: 0.5,
    bo: 'plates',
    lg: 2,
    wu: 0.4,
    a: 'buff',
  },
  demoralizing_shout: {
    c: '#6b5a8c',
    p: 'shadow',
    pw: 1.15,
    sp: 0,
    rg: 2.6,
    sm: 1,
    li: 2,
    lg: 2,
    wu: 0.3,
    a: 'shout',
  },
  sunder_armor: { c: '#dfe6ee', p: 'physical', pw: 0.8, sp: 45, db: 1, li: 0.6, a: 'strike' },
  taunt: { c: '#dfe6ee', p: 'physical', pw: 0.85, sp: 10, rg: 1.8, vr: 1, li: 2.6, a: 'shout' },
  mortal_strike: {
    c: '#e5e9f0',
    p: 'physical',
    pw: 1.3,
    sp: 40,
    vr: 1,
    db: 1,
    bl: 1,
    li: 0.8,
    lg: 1.5,
    wu: 0.4,
    a: 'strike',
  },
  bloodthirst: {
    c: '#c41022',
    p: 'blood',
    pw: 1.2,
    sp: 34,
    rg: 1.4,
    vr: 1,
    db: 1,
    bl: 1,
    li: 0.6,
    lg: 1,
    a: 'strike',
  },
  shield_slam: {
    c: '#bcd0e8',
    p: 'physical',
    pw: 1.2,
    sp: 16,
    rg: 1.6,
    vr: 1,
    db: 1,
    sm: 1,
    li: 1.4,
    lg: 1,
    wu: 0.3,
    a: 'strike',
  },
  berserker_rage: {
    c: '#ff2a14',
    p: 'blood',
    pw: 1.15,
    sp: 20,
    rg: 1.8,
    vr: 1,
    bl: 1,
    li: 2.6,
    bo: 'heartbeat',
    lg: 3.5,
    wu: 0.3,
    a: 'buff',
  },
  fireball: {
    c: '#ff7a2a',
    p: 'fire',
    sp: 36,
    rg: 1,
    db: 1,
    sm: 1,
    b: { v: 17, h: 1.4 },
    lg: 3,
    wu: 1.7,
    a: 'bolt',
  },
  frost_armor: { c: '#bfeaff', p: 'frost', pw: 0.7, bo: 'sparks', lg: 2, a: 'buff' },
  arcane_intellect: { c: '#c9a6ff', p: 'arcane', pw: 0.65, bo: 'halo', lg: 2, a: 'buff' },
  frostbolt: {
    c: '#e8f6ff',
    p: 'frost',
    pw: 0.95,
    sp: 18,
    vr: 1,
    db: 1,
    b: { v: 20, h: 1.1, co: 1 },
    lg: 2,
    a: 'bolt',
  },
  conjure_water: { c: '#aee7ff', p: 'frost', pw: 0.6, lg: 1.5, a: 'buff' },
  conjure_food: {
    c: '#ffcf8a',
    p: 'arcane',
    pw: 0.6,
    sp: 6,
    sm: 1,
    li: 0.5,
    lg: 1.5,
    wu: 2,
    a: 'buff',
  },
  fire_blast: { c: '#ffd23e', p: 'fire', pw: 1.05, sp: 44, vr: 1, a: 'burst' },
  arcane_missiles: {
    c: '#c86bff',
    p: 'arcane',
    pw: 0.95,
    sp: 16,
    b: { v: 22, h: 0.75, vl: 4 },
    a: 'bolt',
  },
  polymorph: { c: '#c86bff', p: 'arcane', pw: 0.85, lg: 4, a: 'cc' },
  frost_nova: { c: '#7fd4ff', p: 'frost', pw: 1.35, sp: 26, db: 1, lg: 3.5, fin: 1, a: 'nova' },
  arcane_explosion: { c: '#c86bff', p: 'arcane', sp: 24, rg: 2, wu: 0.25, a: 'nova' },
  scorch: { c: '#b83a10', p: 'fire', pw: 0.85, sp: 10, sm: 1, a: 'burst' },
  ice_barrier: { c: '#58b8dc', p: 'frost', pw: 1.1, bo: 'plates', lg: 4, a: 'buff' },
  pyroblast: {
    c: '#ff7a2a',
    p: 'fire',
    pw: 1.5,
    sp: 50,
    rg: 2,
    vr: 1,
    db: 1,
    sm: 1,
    li: 0.9,
    b: { v: 20, h: 1.8 },
    lg: 4,
    wu: 2.5,
    a: 'bolt',
  },
  flamestrike: {
    c: '#ff7a2a',
    p: 'fire',
    pw: 1.15,
    sp: 30,
    rg: 2,
    sm: 1,
    li: 0.8,
    lg: 2.5,
    a: 'nova',
  },
  sinister_strike: { c: '#dfe6ee', p: 'physical', pw: 0.85, sp: 14, a: 'strike' },
  eviscerate: {
    c: '#d41f2e',
    p: 'blood',
    pw: 1.45,
    sp: 36,
    db: 1,
    bl: 1,
    li: 0.5,
    wu: 0.2,
    fin: 1,
    a: 'strike',
  },
  garrote: {
    c: '#d41f2e',
    p: 'blood',
    pw: 0.8,
    sp: 0,
    vr: 1,
    sm: 1,
    bl: 1,
    li: 0.3,
    lg: 3.5,
    a: 'strike',
  },
  backstab: { c: '#8a6ab8', p: 'shadow', sp: 8, bl: 1, li: 0.6, a: 'strike' },
  gouge: { c: '#dfe6ee', p: 'physical', pw: 0.85, sp: 12, a: 'strike' },
  cheap_shot: { c: '#dfe6ee', p: 'physical', pw: 0.9, sp: 6, sm: 1, li: 0.3, lg: 2, a: 'strike' },
  evasion: { c: '#9fb8d8', p: 'physical', bo: 'wings', lg: 4, a: 'buff' },
  sap: { c: '#dfe6ee', p: 'physical', pw: 0.7, sp: 4, sm: 1, li: 0.3, lg: 4, a: 'cc' },
  slice_and_dice: { c: '#e8c860', p: 'physical', pw: 1.05, bo: 'sparks', lg: 4, a: 'buff' },
  sprint: {
    c: '#cdd9e6',
    p: 'physical',
    pw: 0.7,
    sp: 0,
    sm: 1,
    bo: 'speedlines',
    lg: 2,
    a: 'buff',
  },
  crippling_poison: {
    c: '#c8ff3c',
    p: 'venom',
    pw: 0.8,
    sp: 6,
    sm: 1,
    li: 0.4,
    lg: 3,
    a: 'strike',
  },
  kidney_shot: { c: '#d41f2e', p: 'blood', pw: 1.2, sp: 20, vr: 1, a: 'strike' },
  expose_armor: {
    c: '#dfe6ee',
    p: 'physical',
    pw: 1.05,
    sp: 34,
    vr: 1,
    db: 1,
    li: 0.6,
    a: 'strike',
  },
  ambush: {
    c: '#2e2640',
    p: 'shadow',
    pw: 1.4,
    sp: 18,
    sm: 1,
    bl: 1,
    li: 0.3,
    lg: 0.6,
    wu: 0.5,
    a: 'strike',
  },
  rupture: { c: '#d41f2e', p: 'blood', pw: 1.15, sp: 0, bl: 1, li: 0.4, lg: 4, a: 'dot' },
  // Growverse original (no upstream spec). A warrior bleed: Rupture's dot
  // anatomy at a lighter power, since Rend is a low-level opener, not a finisher.
  rend: { c: '#c81e28', p: 'blood', pw: 0.9, sp: 0, bl: 1, li: 0.4, lg: 4, a: 'dot' },
  vanish: {
    c: '#241f33',
    p: 'shadow',
    pw: 0.9,
    sp: 0,
    rg: 1.4,
    sm: 1,
    li: 0.3,
    lg: 2.5,
    a: 'buff',
  },
  instant_poison: {
    c: '#8fd455',
    p: 'venom',
    pw: 0.7,
    sp: 10,
    li: 0.5,
    bo: 'weaponGlow',
    lg: 3,
    wu: 0.4,
    a: 'buff',
  },
  adrenaline_rush: {
    c: '#e03a2e',
    p: 'blood',
    pw: 1.25,
    li: 0.6,
    bo: 'heartbeat',
    lg: 3.5,
    a: 'buff',
  },
  deadly_poison: {
    c: '#c8ff3c',
    p: 'venom',
    pw: 0.85,
    sp: 0,
    sm: 1,
    li: 0.3,
    lg: 4,
    wu: 0.6,
    a: 'buff',
  },
  // Dirt Toss: khaki - the color IS the dirt (the dust cone, the poof, the
  // windup all ride it), not the old pale steel
  blind: { c: '#c2b280', p: 'physical', pw: 0.8, sp: 0, db: 1, sm: 1, li: 0.3, lg: 4, a: 'cc' },
  stealth: { c: '#3a3450', p: 'shadow', pw: 0.5, sp: 0, sm: 1, li: 0.3, lg: 2, a: 'buff' },
  seal_of_righteousness: {
    c: '#ffd76a',
    p: 'gold',
    pw: 0.8,
    bo: 'weaponGlow',
    lg: 3,
    wu: 0.5,
    a: 'buff',
  },
  holy_light: { c: '#ffd970', p: 'holy', li: 0.8, wu: 2.5, a: 'heal' },
  devotion_aura: { c: '#f7edc6', p: 'holy', pw: 0.6, bo: 'halo', lg: 2, a: 'buff' },
  judgement: {
    c: '#ffd970',
    p: 'gold',
    pw: 1.3,
    sp: 26,
    rg: 2,
    li: 0.7,
    wu: 0.5,
    fin: 1,
    a: 'burst',
  },
  blessing_of_might: {
    c: '#d4941e',
    p: 'gold',
    pw: 0.7,
    sp: 14,
    li: 1.3,
    bo: 'wings',
    lg: 2,
    a: 'buff',
  },
  divine_protection: { c: '#ffe9a8', p: 'holy', pw: 0.9, lg: 3.5, a: 'buff' },
  hammer_of_justice: { c: '#ffd970', p: 'gold', sp: 18, vr: 1, db: 1, li: 0.9, lg: 3, a: 'cc' },
  lay_on_hands: { c: '#ffd970', p: 'holy', pw: 1.6, db: 1, li: 0.7, wu: 0.8, a: 'heal' },
  flash_of_light: { c: '#ffd970', p: 'holy', pw: 0.8, sp: 12, vr: 1, li: 1.1, wu: 1.5, a: 'heal' },
  exorcism: { c: '#ffd970', p: 'holy', pw: 1.1, a: 'burst' },
  consecration: { c: '#ffd970', p: 'gold', sp: 18, li: 0.6, lg: 4, wu: 0.5, a: 'nova' },
  righteous_fury: {
    c: '#ff7a2a',
    p: 'fire',
    pw: 0.75,
    bo: 'heartbeat',
    lg: 2.5,
    wu: 0.4,
    a: 'buff',
  },
  retribution_aura: {
    c: '#ffb347',
    p: 'gold',
    pw: 0.65,
    sp: 12,
    li: 0.5,
    bo: 'sparks',
    lg: 3,
    a: 'buff',
  },
  raptor_strike: {
    c: '#e03a24',
    p: 'physical',
    pw: 1.15,
    sp: 26,
    vr: 1,
    db: 1,
    bl: 1,
    li: 0.6,
    wu: 0.5,
    a: 'strike',
  },
  aspect_of_the_hawk: {
    c: '#8fc6ff',
    p: 'storm',
    sp: 14,
    rg: 1.6,
    vr: 1,
    li: 1.6,
    bo: 'wings',
    lg: 3.5,
    wu: 0.3,
    a: 'buff',
  },
  serpent_sting: { c: '#c8ff3c', p: 'venom', pw: 0.85, sp: 8, db: 1, li: 0.5, lg: 4, a: 'dot' },
  arcane_shot: { c: '#c86bff', p: 'arcane', pw: 0.95, b: { v: 40, h: 0.7 }, a: 'bolt' },
  concussive_shot: {
    c: '#dfe6ee',
    p: 'physical',
    pw: 0.8,
    sp: 0,
    rg: 1,
    vr: 1,
    db: 1,
    sm: 1,
    li: 0.6,
    b: { v: 30, h: 0.9 },
    lg: 2,
    a: 'bolt',
  },
  mongoose_bite: { c: '#a4ff4f', p: 'physical', pw: 0.95, sp: 18, vr: 1, li: 0.6, a: 'strike' },
  wing_clip: {
    c: '#dfe6ee',
    p: 'physical',
    pw: 0.7,
    sp: 6,
    db: 1,
    sm: 1,
    bl: 1,
    li: 0.4,
    lg: 2,
    a: 'strike',
  },
  tame_beast: {
    c: '#8cd07a',
    p: 'nature',
    pw: 0.8,
    sp: 8,
    sm: 1,
    li: 0.6,
    lg: 3,
    wu: 2.5,
    a: 'summon',
  },
  dismiss_pet: { c: '#86cfae', p: 'nature', pw: 0.5, lg: 1.5, a: 'buff' },
  revive_pet: { c: '#8cd07a', p: 'nature', pw: 0.75, wu: 1.5, a: 'summon' },
  aspect_of_the_monkey: {
    c: '#8fd455',
    p: 'physical',
    pw: 0.7,
    sp: 22,
    vr: 1,
    li: 1.2,
    bo: 'sparks',
    lg: 3,
    a: 'buff',
  },
  aspect_of_the_cheetah: {
    c: '#e8a34c',
    p: 'physical',
    pw: 0.8,
    sp: 10,
    rg: 1.4,
    db: 1,
    sm: 1,
    li: 1.4,
    bo: 'speedlines',
    lg: 3,
    wu: 0.3,
    a: 'buff',
  },
  aimed_shot: {
    c: '#dfe6ee',
    p: 'physical',
    pw: 1.45,
    sp: 48,
    rg: 1,
    vr: 1,
    db: 1,
    li: 0.7,
    b: { v: 48 },
    wu: 2.5,
    fin: 1,
    a: 'bolt',
  },
  rapid_fire: {
    c: '#ff6242',
    p: 'physical',
    pw: 0.9,
    sp: 10,
    li: 0.5,
    b: { v: 45, h: 0.6, vl: 5 },
    bo: 'heartbeat',
    lg: 3,
    wu: 0.4,
    a: 'buff',
  },
  volley: {
    c: '#dfe6ee',
    p: 'physical',
    pw: 1.05,
    sp: 16,
    rg: 1.2,
    db: 1,
    sm: 1,
    li: 0.4,
    lg: 3,
    wu: 0.4,
    a: 'nova',
  },
  feed_pet: { c: '#8cd07a', p: 'nature', pw: 0.6, sp: 12, vr: 1, li: 0.6, lg: 2.5, a: 'summon' },
  abandon_pet: { c: '#8cd07a', p: 'nature', pw: 0.55, sp: 0, sm: 1, li: 0.4, lg: 2.2, a: 'summon' },
  smite: { c: '#ffd970', p: 'holy', pw: 0.9, sp: 26, rg: 1, li: 0.5, a: 'burst' },
  lesser_heal: { c: '#f2f6ff', p: 'holy', pw: 0.65, a: 'heal' },
  power_word_fortitude: { c: '#ffd9a0', p: 'holy', pw: 0.6, bo: 'heartbeat', lg: 2, a: 'buff' },
  shadow_word_pain: { c: '#8a6ab8', p: 'shadow', pw: 0.85, sp: 4, sm: 1, li: 0.6, lg: 4, a: 'dot' },
  power_word_shield: { c: '#eef4ff', p: 'holy', pw: 0.95, bo: 'plates', lg: 4, a: 'buff' },
  renew: { c: '#f2f6ff', p: 'holy', pw: 0.6, lg: 4, a: 'heal' },
  mind_blast: {
    c: '#8a6ab8',
    p: 'shadow',
    pw: 1.3,
    sp: 20,
    rg: 1,
    vr: 1,
    sm: 1,
    fin: 1,
    a: 'burst',
  },
  heal: { c: '#f2f6ff', p: 'holy', a: 'heal' },
  mind_flay: { c: '#8a6ab8', p: 'shadow', pw: 1.05, sp: 8, sm: 1, li: 1.3, a: 'beam' },
  flash_heal: { c: '#f2f6ff', p: 'holy', pw: 0.8, sp: 18, vr: 1, li: 1.2, a: 'heal' },
  lightning_bolt: {
    c: '#8fd0ff',
    p: 'storm',
    pw: 1.25,
    b: { v: 30, j: 1, co: 1 },
    lg: 3.2,
    wu: 1.7,
    fin: 1,
    a: 'bolt',
  },
  rockbiter_weapon: {
    c: '#b08850',
    p: 'physical',
    pw: 0.75,
    sp: 6,
    rg: 1.2,
    db: 1,
    bo: 'weaponGlow',
    lg: 2.5,
    wu: 0.5,
    a: 'buff',
  },
  healing_wave: { c: '#7fd4ff', p: 'frost', pw: 0.9, sp: 10, vr: 1, li: 1.2, a: 'heal' },
  earth_shock: {
    c: '#dfe6ee',
    p: 'physical',
    pw: 1.05,
    sp: 8,
    rg: 1.3,
    db: 1,
    sm: 1,
    li: 0.7,
    wu: 0.4,
    a: 'burst',
  },
  lightning_shield: { c: '#7fd6ff', p: 'storm', pw: 0.65, bo: 'sparks', lg: 4, wu: 0.4, a: 'buff' },
  flame_shock: { c: '#ff7a2a', p: 'fire', pw: 0.9, sp: 18, sm: 1, li: 0.8, lg: 4, a: 'dot' },
  flametongue_weapon: {
    c: '#ff8c3a',
    p: 'fire',
    pw: 0.75,
    sp: 16,
    sm: 1,
    li: 1.3,
    bo: 'weaponGlow',
    lg: 3,
    a: 'buff',
  },
  frost_shock: {
    c: '#7fd4ff',
    p: 'frost',
    pw: 0.9,
    sp: 0,
    vr: 1,
    db: 1,
    li: 0.8,
    lg: 2.5,
    a: 'burst',
  },
  frostbrand_weapon: {
    c: '#4f9fd8',
    p: 'frost',
    pw: 0.75,
    sp: 0,
    vr: 1,
    db: 1,
    li: 0.9,
    bo: 'weaponGlow',
    lg: 3,
    wu: 0.55,
    a: 'buff',
  },
  ghost_wolf: { c: '#b4a8e0', p: 'moon', pw: 0.6, bo: 'speedlines', lg: 2, a: 'buff' },
  earthquake: {
    c: '#dfe6ee',
    p: 'physical',
    pw: 1.3,
    sp: 6,
    rg: 2,
    db: 1,
    sm: 1,
    li: 0.5,
    lg: 6,
    wu: 0.7,
    a: 'nova',
  },
  stormstrike: {
    c: '#8fd6ff',
    p: 'storm',
    pw: 1.3,
    sp: 48,
    vr: 1,
    db: 1,
    li: 1.5,
    wu: 0.45,
    a: 'strike',
  },
  shadow_bolt: { c: '#8a6ab8', p: 'shadow', sp: 22, sm: 1, b: { v: 21, h: 1.3, co: 1 }, a: 'bolt' },
  summon_imp: { c: '#ff7a2a', p: 'fire', pw: 0.85, sp: 26, sm: 1, li: 1.2, lg: 2, a: 'summon' },
  demon_skin: { c: '#8b3ff5', p: 'shadow', pw: 0.6, bo: 'plates', lg: 3.5, a: 'buff' },
  immolate: { c: '#ff7a2a', p: 'fire', pw: 0.9, sp: 36, sm: 1, lg: 4, a: 'dot' },
  corruption: { c: '#c8ff3c', p: 'venom', pw: 0.85, sp: 6, sm: 1, lg: 4, a: 'dot' },
  life_tap: { c: '#ff4a5a', p: 'blood', pw: 0.65, bl: 1, bo: 'heartbeat', lg: 1.5, a: 'buff' },
  summon_voidwalker: {
    c: '#8a6ab8',
    p: 'shadow',
    pw: 1.1,
    db: 1,
    sm: 1,
    li: 1.2,
    lg: 2.5,
    a: 'summon',
  },
  curse_of_agony: { c: '#8a6ab8', p: 'shadow', pw: 1.05, sp: 10, lg: 4, a: 'dot' },
  drain_life: { c: '#d41f2e', p: 'blood', sp: 12, bl: 1, li: 1.6, lg: 2, a: 'beam' },
  fear: { c: '#8a6ab8', p: 'shadow', pw: 0.85, li: 1.5, lg: 4, a: 'cc' },
  searing_pain: {
    c: '#ffd23e',
    p: 'fire',
    pw: 0.95,
    sp: 44,
    li: 1.4,
    b: { v: 30, h: 0.9 },
    a: 'bolt',
  },
  shadowburn: {
    c: '#8a6ab8',
    p: 'shadow',
    pw: 1.4,
    sp: 50,
    rg: 1,
    vr: 1,
    db: 1,
    sm: 1,
    lg: 2,
    fin: 1,
    a: 'burst',
  },
  summon_succubus: {
    c: '#d966b8',
    p: 'shadow',
    pw: 0.9,
    sp: 18,
    sm: 1,
    li: 1.1,
    lg: 2,
    wu: 2,
    a: 'summon',
  },
  summon_felhunter: {
    c: '#b48cff',
    p: 'shadow',
    pw: 0.95,
    sp: 24,
    sm: 1,
    li: 1.2,
    lg: 2,
    wu: 2,
    a: 'summon',
  },
  summon_felguard: {
    c: '#8a6ab8',
    p: 'shadow',
    pw: 1.15,
    sp: 20,
    rg: 1.4,
    db: 1,
    sm: 1,
    li: 1.1,
    lg: 2.5,
    wu: 2.2,
    a: 'summon',
  },
  summon_infernal: {
    c: '#ff7a2a',
    p: 'fire',
    pw: 1.6,
    sp: 40,
    rg: 2,
    vr: 1,
    db: 1,
    sm: 1,
    li: 2,
    lg: 3,
    wu: 2.4,
    a: 'summon',
  },
  summon_doomguard: {
    c: '#8b2a4a',
    p: 'shadow',
    pw: 1.45,
    sp: 14,
    vr: 1,
    sm: 1,
    li: 1.7,
    lg: 3,
    wu: 2.4,
    a: 'summon',
  },
  rain_of_fire: {
    c: '#ff7a2a',
    p: 'fire',
    pw: 1.15,
    sp: 30,
    db: 1,
    sm: 1,
    li: 0.9,
    lg: 4,
    wu: 0.4,
    a: 'dot',
  },
  wrath: { c: '#8cd07a', p: 'nature', pw: 0.9, li: 0.6, b: { v: 24, co: 1 }, a: 'bolt' },
  healing_touch: { c: '#8cd07a', p: 'nature', a: 'heal' },
  mark_of_the_wild: { c: '#b9d178', p: 'nature', pw: 0.6, bo: 'leaves', lg: 3, a: 'buff' },
  moonfire: { c: '#b4a8e0', p: 'moon', pw: 0.95, sp: 10, li: 0.5, lg: 4, a: 'dot' },
  rejuvenation: { c: '#8cd07a', p: 'nature', pw: 0.65, lg: 4, a: 'heal' },
  thorns: { c: '#3f7a2e', p: 'venom', pw: 0.65, bo: 'sparks', lg: 3.5, a: 'buff' },
  entangling_roots: { c: '#8cd07a', p: 'nature', pw: 0.75, db: 1, sm: 1, li: 0.3, lg: 4, a: 'cc' },
  bear_form: { c: '#9a6a3a', p: 'nature', pw: 0.75, rg: 1.4, db: 1, sm: 1, lg: 2, a: 'buff' },
  bear_charge: { c: '#dfe6ee', p: 'physical', sp: 14, rg: 1.5, db: 1, sm: 1, li: 0.6, a: 'dash' },
  maul: { c: '#dfe6ee', p: 'physical', sp: 10, rg: 1.1, db: 1, li: 0.4, a: 'strike' },
  growl: {
    c: '#ff5f45',
    p: 'physical',
    pw: 1.05,
    sp: 10,
    rg: 2.2,
    vr: 1,
    db: 1,
    sm: 1,
    li: 1.6,
    a: 'shout',
  },
  demoralizing_roar: {
    c: '#7d6b9e',
    p: 'physical',
    pw: 1.1,
    sp: 6,
    rg: 3,
    db: 1,
    sm: 1,
    li: 1.3,
    a: 'shout',
  },
  cat_form: { c: '#8fa3c8', p: 'moon', pw: 0.7, lg: 2, a: 'buff' },
  prowl: { c: '#26303f', p: 'moon', pw: 0.5, lg: 2, a: 'buff' },
  rake: { c: '#d41f2e', p: 'blood', pw: 0.9, sp: 8, bl: 1, li: 0.4, lg: 4, a: 'strike' },
  claw: { c: '#dfe6ee', p: 'physical', pw: 0.85, sp: 8, li: 0.3, a: 'strike' },
  regrowth: { c: '#8cd07a', p: 'nature', pw: 0.9, sp: 12, vr: 1, lg: 3.5, a: 'heal' },
  ferocious_bite: {
    c: '#d41f2e',
    p: 'blood',
    pw: 1.3,
    sp: 30,
    rg: 1.5,
    vr: 1,
    db: 1,
    bl: 1,
    li: 0.5,
    lg: 1.5,
    a: 'strike',
  },
  barkskin: {
    c: '#7a8f66',
    p: 'nature',
    pw: 0.7,
    rg: 1.2,
    db: 1,
    li: 0.5,
    bo: 'plates',
    lg: 4,
    a: 'buff',
  },
  swipe: { c: '#dfe6ee', p: 'physical', pw: 0.85, sp: 18, db: 1, sm: 1, li: 0.5, a: 'nova' },
  starfire: {
    c: '#b4a8e0',
    p: 'moon',
    pw: 1.5,
    sp: 40,
    rg: 1.6,
    vr: 1,
    db: 1,
    sm: 1,
    li: 0.5,
    b: { v: 18, h: 1.7, co: 1 },
    wu: 2.5,
    fin: 1,
    a: 'bolt',
  },
  travel_form: {
    c: '#d9c060',
    p: 'nature',
    pw: 0.6,
    sp: 0,
    sm: 1,
    li: 0.5,
    bo: 'speedlines',
    lg: 2,
    a: 'buff',
  },
  enrage: {
    c: '#d84a2a',
    p: 'blood',
    pw: 0.8,
    sp: 10,
    rg: 1.2,
    db: 1,
    sm: 1,
    li: 0.8,
    bo: 'heartbeat',
    lg: 3,
    wu: 0.3,
    a: 'buff',
  },
  bash: {
    c: '#dfe6ee',
    p: 'physical',
    pw: 0.9,
    sp: 12,
    vr: 1,
    db: 1,
    sm: 1,
    li: 0.5,
    lg: 1.5,
    a: 'strike',
  },
  faerie_fire: {
    c: '#e79aff',
    p: 'nature',
    pw: 0.6,
    sp: 6,
    li: 0.4,
    b: { v: 22, h: 0.7 },
    lg: 4,
    a: 'bolt',
  },
  hibernate: { c: '#cfe8ff', p: 'nature', pw: 0.7, sp: 8, sm: 1, li: 0.4, lg: 4, wu: 1.5, a: 'cc' },
  dash: {
    c: '#6f8fd8',
    p: 'moon',
    pw: 0.7,
    sp: 0,
    sm: 1,
    li: 0.4,
    bo: 'speedlines',
    lg: 3,
    a: 'buff',
  },
  pounce: { c: '#b4a8e0', p: 'moon', pw: 0.95, sp: 6, sm: 1, li: 0.3, lg: 1.5, a: 'strike' },
  insect_swarm: { c: '#b7c94a', p: 'nature', pw: 0.9, sp: 14, li: 0.4, lg: 4, a: 'dot' },
  tigers_fury: {
    c: '#b81f3c',
    p: 'blood',
    pw: 0.9,
    sp: 10,
    bl: 1,
    li: 0.7,
    bo: 'heartbeat',
    lg: 3,
    a: 'buff',
  },
  rip: { c: '#d41f2e', p: 'blood', pw: 1.1, sp: 8, vr: 1, bl: 1, li: 0.5, lg: 4, a: 'dot' },
  hurricane: {
    c: '#b6c0a8',
    p: 'storm',
    pw: 1.2,
    sp: 22,
    rg: 2,
    db: 1,
    sm: 1,
    li: 1.1,
    lg: 6,
    wu: 0.6,
    a: 'nova',
  },
};
